name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
        node-version: 16

      - name: Install yarn packages
        run: yarn ci

      - name: Prettier code format check
        run: yarn run format-check

      - name: ESLint code check
        run: yarn run lint
