name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install npm packages
        run: npm ci

      - name: Prettier code format check
        run: npm run format-check

      - name: ESLint code check
        run: npm run lint
