name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install yarn packages
        run: yarn ci

      - name: Install webpack
        run: yarn global add webpack

      - name: Prettier code format check
        run: yarn run format

      - name: ESLint code check
        run: yarn run lint

      - name: Deploy to Firebae
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ARES_SHOP_CLIENT }}'
          channelId: live
          projectId: ares-shop-client
