name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get project
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install yarn packages
        run: yarn ci

      - name: Install webpack
        run: yarn global add webpack

      - name: Prettier code format check
        run: yarn run format

      - name: ESLint code check
        run: yarn run lint:fix

      - name: Build app
        run: yarn run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'ares-shop-client'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
